### ISSUE TITLE
Not clear about the rxEnable

### ISSUE THREAD

**Issue by X-Ryl669** [nomel/beaglebone#3]
In the example, you set the state to rxEnablePullNone, then you set the value like if the GPIO was set to output mode.

It's a bit unclear to me. As I understand it, the receivedEnable mode should be set only for GPIO used as input, not for GPIO used as output. Am I missing something?

**Comment by nomel** [comment]
It saves a negligible amount of power, that is all. Also, if you're using
the sysfs interface and leave it off, you wont be able to change the pin
direction property from output to input without messing with the overlay
state.

Also, the concept of input and output is somewhat loose from the hardware
perspective, there's a circuit that drives a voltage, and there's a circuit
that reads a voltage. They're not mutually exclusive. For example, I use
low level register reads and writes in my gpio library. When I read the
state of an output pin, I don't read the output drive state, I read the
state as sampled by the receiver circuit. The first is an assumption (sysfs
interface uses this), the second is a measurement. This lets me know if
I've blown up a driver or if a pin that's driving high is being pulled low
by something like a short (or the other way around). In what I'm doing, I
can't assume a pin is functioning properly.

**Comment by X-Ryl669** [comment]
Ok, it's more clear now.
